apiVersion: v1
kind: ConfigMap
metadata:
  name: reservations-config
  namespace: reservations-staging
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/reservations"
  SPRING_JPA_SHOW_SQL: "true"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics"
